# Generated by Django 3.2.5 on 2021-07-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_meeting_meetingparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
