# Generated by Django 3.2.5 on 2021-07-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210724_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('complete', 'Complete')], default='todo', max_length=15),
        ),
        migrations.DeleteModel(
            name='Column',
        ),
    ]
