# Generated by Django 3.2.5 on 2021-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
