# Generated by Django 3.2.5 on 2021-07-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_taskmember_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDpendency',
            new_name='TaskDependency',
        ),
    ]
