# Generated by Django 3.2.5 on 2021-07-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210725_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
