# Generated by Django 3.2.5 on 2021-07-25 04:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_workspace_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=core.models.upload_to)),
            ],
        ),
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
