# Generated by Django 3.2.5 on 2021-07-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prismuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prismuser',
            name='phone',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
