# Generated by Django 3.2.5 on 2021-07-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210723_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prismuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='password'),
        ),
    ]
