# Generated by Django 3.2.5 on 2021-07-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_prismuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prismuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
